export const ServerTypes = [
    "Vanilla",
    "Modded"
]

export const ServerFeatures = [
  'Pokémon',         
  'Bosses',
  'Classes',         
  'Custom Content',
  'Dungeons',        
  'Economy',
  'Media',           
  'OP',
  'Personal Worlds', 
  'Plots',
  'PvE',             
  'PvP',
  'Questing',        
  'Teams'
]

export const ServerGameplays = [
  'Anarchy',      
  'Battle Royale',
  'Bed Wars',     
  'Factions',
  'Gens',         
  'Kit PvP',
  'Lifesteal',    
  'Microgames',
  'Minigames',    
  'One Block',
  'Parkour',      
  'Prison',
  'Racing',       
  'RPG',
  'Skyblock',     
  'Towns',
  'Vanilla Like'
]

export const ServerMetas = [
  'Adventure Mode',
  'Creative Mode',
  'Crossplay',
  'Hardcore Mode',
  'Keep Inventory',
  'Network',
  'Offline Mode',
  'Survival Mode',
  'Whitelisted',
  'World Resets'
]

export const ServerCommunities = [
  'Competitive',
  'Creator Community',
  'MMO',
  'Recording SMP',
  'Roleplay',
  'SMP',
  'Social',
  'Technical'
]

export const ServerRegions = [
  'Asia',
  'Australia',
  'Europe',
  'Middle East',
  'Russia',
  'South America',
  'US East',
  'US West'
]

export const ServerLanguages = [
  'English',    
  'Afrikaans', 
  'Albanian',    
  'Amharic',
  'Arabic',     
  'Armenian',  
  'Azerbaijani', 
  'Basque',
  'Belarusian', 
  'Bengali',   
  'Bosnian',     
  'Bulgarian',
  'Burmese',    
  'Catalan',   
  'Chinese',     
  'Croatian',
  'Czech',      
  'Danish',    
  'Dutch',       
  'Esperanto',
  'Estonian',   
  'Filipino',  
  'Finnish',     
  'French',
  'Galician',   
  'Georgian',  
  'German',      
  'Greek',
  'Hebrew',     
  'Hindi',     
  'Hungarian',   
  'Icelandic',
  'Indonesian', 
  'Irish',     
  'Italian',     
  'Japanese',
  'Kannada',    
  'Kazakh',    
  'Khmer',       
  'Korean',
  'Lao',        
  'Latvian',   
  'Lithuanian',  
  'Macedonian',
  'Malay',      
  'Malayalam', 
  'Marathi',     
  'Mongolian',
  'Nepali',     
  'Norwegian', 
  'Persian',     
  'Polish',
  'Portuguese', 
  'Punjabi',   
  'Romanian',    
  'Russian',
  'Serbian',    
  'Sinhala',   
  'Slovak',      
  'Slovenian',
  'Spanish',    
  'Swahili',   
  'Swedish',     
  'Tamil',
  'Telugu',     
  'Thai',      
  'Turkish',     
  'Ukrainian',
  'Urdu',       
  'Uzbek',     
  'Vietnamese',  
  'Yoruba',
  'Zulu'
]